-- =============================================================================
-- LPG Stock Recon App — Unified Schema (Python Profile Integration)
-- Project: uxolvqsugwzxheuzvrtr
-- =============================================================================

-- 1. OPERATIONAL TABLES (For App State)
CREATE TABLE IF NOT EXISTS sessions (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  date          DATE NOT NULL,
  current_state TEXT NOT NULL DEFAULT 'OPEN',
  locked        BOOLEAN NOT NULL DEFAULT false,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS counts (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id UUID NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
  data       JSONB NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Upload History
CREATE TABLE IF NOT EXISTS sync_logs (
    id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    filename       TEXT NOT NULL,
    file_type      TEXT NOT NULL,
    records_synced INTEGER NOT NULL,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 2. TRANSACTION LOG TABLES (For ERP Ingestion)
CREATE TABLE IF NOT EXISTS transaction_headers (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entry_type    TEXT,
    period        INTEGER,
    account_no    TEXT,
    account_name  TEXT,
    doc_no        TEXT,
    ref_no        TEXT,
    description   TEXT,
    order_no      TEXT,
    batch_ref     TEXT,
    tx_date       DATE,
    amount_excl   NUMERIC,
    tax_amount    NUMERIC,
    tax_code      TEXT,
    discount      NUMERIC,
    flag          TEXT,
    source_file   TEXT,
    fingerprint   TEXT UNIQUE,
    created_at    TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_headers_account_no ON transaction_headers(account_no);
CREATE INDEX IF NOT EXISTS idx_headers_doc_no ON transaction_headers(doc_no);
CREATE INDEX IF NOT EXISTS idx_headers_tx_date ON transaction_headers(tx_date);

CREATE TABLE IF NOT EXISTS transaction_items (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entry_type    TEXT,
    period        INTEGER,
    account_no    TEXT,
    doc_no        TEXT,
    stock_no      TEXT,
    description   TEXT,
    category      TEXT,
    product_group TEXT,
    brand         TEXT,
    order_no      TEXT,
    tx_date       DATE,
    qty           NUMERIC,
    retail_price  NUMERIC,
    cost_price    NUMERIC,
    reference     TEXT,
    rep_code      TEXT,
    user_code     TEXT,
    location      TEXT,
    tax_code      INTEGER,
    line_tax      NUMERIC,
    rep_name      TEXT,
    account_name  TEXT,
    source_file   TEXT,
    fingerprint   TEXT UNIQUE,
    created_at    TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_items_doc_no ON transaction_items(doc_no);
CREATE INDEX IF NOT EXISTS idx_items_stock_no ON transaction_items(stock_no);

-- 3. RECONCILIATION VIEWS
CREATE OR REPLACE VIEW unique_accounts AS
SELECT 
    account_no,
    MAX(account_name) as account_name
FROM transaction_headers
WHERE account_no IS NOT NULL
GROUP BY account_no;

CREATE OR REPLACE VIEW reconciliation_summary AS
SELECT 
    h.account_no,
    h.account_name,
    h.doc_no,
    h.tx_date,
    h.entry_type,
    h.amount_excl as ledger_excl,
    h.tax_amount as ledger_tax,
    (h.amount_excl + h.tax_amount) as ledger_total,
    i.calc_total as operational_total,
    CASE 
        WHEN h.entry_type = 'Invoice' 
             AND ABS((h.amount_excl + h.tax_amount) - i.calc_total) > 0.01 
             AND ABS(h.amount_excl - i.calc_total) < 0.01 
        THEN true 
        ELSE false 
    END as is_double_taxed,
    (h.amount_excl + h.tax_amount - i.calc_total) as tax_distortion_amount,
    i.calc_lpg,
    i.calc_cyl,
    i.calc_total,
    i.lpg_qty,
    i.cyl_qty
FROM (
    SELECT 
        account_no, 
        MAX(account_name) as account_name, 
        doc_no, 
        tx_date, 
        entry_type, 
        SUM(amount_excl) as amount_excl, 
        SUM(tax_amount) as tax_amount
    FROM transaction_headers
    GROUP BY account_no, doc_no, tx_date, entry_type
) h
LEFT JOIN (
    SELECT 
        doc_no,
        account_no,
        SUM(
            CASE 
                WHEN category = 'LPG' OR stock_no IN ('901', '9.3', '9.4', '19.4', '1901') OR stock_no LIKE 'S%' THEN 
                    (CASE WHEN (retail_price * qty) < 0 THEN (retail_price * qty) - line_tax ELSE (retail_price * qty) + line_tax END)
                ELSE 0 
            END
        ) as calc_lpg,
        SUM(
            CASE 
                WHEN category = 'CYL' OR stock_no IN ('9.1', '14.1', '19.1', 'S.1', 'D.1', 'FL.1') OR stock_no LIKE '9%' OR stock_no LIKE '19%' OR stock_no LIKE '48%' THEN 
                    (CASE WHEN (retail_price * qty) < 0 THEN (retail_price * qty) - line_tax ELSE (retail_price * qty) + line_tax END)
                ELSE 0 
            END
        ) as calc_cyl,
        SUM(
            CASE WHEN (retail_price * qty) < 0 THEN (retail_price * qty) - line_tax ELSE (retail_price * qty) + line_tax END
        ) as calc_total,
        SUM(CASE WHEN category = 'LPG' OR stock_no IN ('901', '9.3', '9.4', '19.4', '1901') OR stock_no LIKE 'S%' THEN qty ELSE 0 END) as lpg_qty,
        SUM(CASE WHEN category = 'CYL' OR stock_no IN ('9.1', '14.1', '19.1', 'S.1', 'D.1', 'FL.1') OR stock_no LIKE '9%' OR stock_no LIKE '19%' OR stock_no LIKE '48%' THEN qty ELSE 0 END) as cyl_qty
    FROM transaction_items
    GROUP BY doc_no, account_no
) i ON h.doc_no = i.doc_no AND h.account_no = i.account_no;

-- 4. DISPATCH MODULE TABLES
CREATE TABLE IF NOT EXISTS customers (
    account_code     TEXT PRIMARY KEY,
    name             TEXT NOT NULL,
    whatsapp_number  TEXT NOT NULL,
    created_at       TIMESTAMPTZ DEFAULT now(),
    updated_at       TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS invoice_dispatch_logs (
    id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    doc_no           TEXT NOT NULL,
    sent_at          TIMESTAMPTZ DEFAULT now(),
    status           TEXT NOT NULL CHECK (status IN ('PENDING', 'SENT', 'FAILED', 'DELIVERED')),
    error_details    TEXT,
    signed_doc_url   TEXT,
    merged_doc_url   TEXT,
    actor_id         UUID DEFAULT auth.uid(),
    created_at       TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_dispatch_logs_doc_no ON invoice_dispatch_logs(doc_no);

-- 5. DISPATCH VIEWS
CREATE OR REPLACE VIEW dispatch_eligible_invoices AS
SELECT DISTINCT ON (h.doc_no)
    h.doc_no,
    h.tx_date,
    h.account_no,
    h.account_name,
    (h.amount_excl + h.tax_amount) as amount_inc,
    c.whatsapp_number,
    l.status as last_status,
    l.sent_at as last_sent_at
FROM transaction_headers h
LEFT JOIN customers c ON h.account_no = c.account_code
LEFT JOIN invoice_dispatch_logs l ON h.doc_no = l.doc_no
WHERE h.entry_type = 'Invoice'
ORDER BY h.doc_no, l.sent_at DESC;

-- 6. STORAGE BUCKETS (Managed via storage schema)
-- Note: Bucket creation via SQL requires the storage schema extensions.
INSERT INTO storage.buckets (id, name, public)
VALUES ('invoice-documents', 'invoice-documents', true)
ON CONFLICT (id) DO NOTHING;

-- RLS for Storage
CREATE POLICY "Clerks can upload invoices"
ON storage.objects FOR INSERT
TO authenticated
WITH CHECK (bucket_id = 'invoice-documents');

CREATE POLICY "Clerks and Managers can view invoices"
ON storage.objects FOR SELECT
TO authenticated
USING (bucket_id = 'invoice-documents');

CREATE POLICY "Managers can delete invoices"
ON storage.objects FOR DELETE
TO authenticated
USING (bucket_id = 'invoice-documents' AND (auth.jwt() ->> 'role') = 'Depot Manager');

-- 7. FINANCIAL CONTROL & AUDIT TABLES
CREATE TABLE IF NOT EXISTS financial_corrections (
    id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    correction_id     TEXT NOT NULL UNIQUE, -- e.g., 'LSR-4'
    type              TEXT NOT NULL,        -- e.g., 'ERP_MAPPING_FIX'
    severity          TEXT NOT NULL,        -- e.g., 'CRITICAL'
    affected_module   TEXT NOT NULL,        -- e.g., 'erpImportEngine'
    financial_impact  NUMERIC,              -- e.g., 1657.40
    root_cause        TEXT NOT NULL,        -- e.g., 'INCLUSIVE_AMOUNT_TREATED_AS_EXCLUSIVE'
    fix_branch        TEXT NOT NULL,        -- e.g., 'fix/LSR-4'
    status            TEXT NOT NULL CHECK (status IN ('PENDING', 'DEPLOYED', 'REVERTED')),
    date_detected     TEXT,                 -- e.g., '2026-04'
    date_fixed        TIMESTAMPTZ DEFAULT now(),
    validation_required BOOLEAN DEFAULT true,
    before_snapshot   JSONB,                -- Financial snapshot before fix
    after_snapshot    JSONB,                -- Financial snapshot after fix
    created_at        TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_corrections_id ON financial_corrections(correction_id);

-- 8. RECEIPT EXTRACTION MODULE (Vision-model OCR + human-in-the-loop review)
CREATE TABLE IF NOT EXISTS receipt_extractions (
    id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    image_url         TEXT NOT NULL,
    document_type     TEXT,             -- e.g. 'delivery_note', 'cylinder_returns'
    supplier_name     TEXT,
    document_number   TEXT,
    document_date     DATE,
    extracted_data    JSONB NOT NULL,   -- raw structured result from the vision model
    system_confidence INTEGER NOT NULL, -- 0-100, model's own overall confidence
    status            TEXT NOT NULL DEFAULT 'PENDING_REVIEW'
                        CHECK (status IN ('PENDING_REVIEW', 'CONFIRMED', 'REJECTED')),
    decision          TEXT CHECK (decision IN ('ACCEPT', 'REJECT', 'MODIFY', 'ESCALATE')),
    reviewed_data     JSONB,            -- human-corrected version of extracted_data, if modified
    human_confidence  INTEGER,
    reason_codes      TEXT[],
    notes             TEXT,
    reviewed_by       TEXT,
    reviewed_at       TIMESTAMPTZ,
    actor_id          UUID DEFAULT auth.uid(),
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_receipt_extractions_status ON receipt_extractions(status);
CREATE INDEX IF NOT EXISTS idx_receipt_extractions_document_number ON receipt_extractions(document_number);

-- Storage bucket for the source receipt/delivery-note photos
INSERT INTO storage.buckets (id, name, public)
VALUES ('receipt-images', 'receipt-images', true)
ON CONFLICT (id) DO NOTHING;

CREATE POLICY "Staff can upload receipt images"
ON storage.objects FOR INSERT
TO authenticated
WITH CHECK (bucket_id = 'receipt-images');

CREATE POLICY "Staff can view receipt images"
ON storage.objects FOR SELECT
TO authenticated
USING (bucket_id = 'receipt-images');

CREATE POLICY "Managers can delete receipt images"
ON storage.objects FOR DELETE
TO authenticated
USING (bucket_id = 'receipt-images' AND (auth.jwt() ->> 'role') = 'Depot Manager');
