-- ============================================================================
-- DRAFT — NOT APPLIED. For human review only.
-- Phase 2 of Orders-Module -> LPG-Stock-Recon migration.
--
-- Safety constraints honored:
--   * Every ALTER TABLE against an existing table adds nullable columns only,
--     no default that rewrites existing rows, no drops/renames.
--   * `customers` (2 rows, WhatsApp-bot) is NOT touched.
--   * `commercial_customers` (536 rows) gets additive columns only; existing
--     `notes` column is reused, not duplicated (see comment below).
--   * `products` (0 rows, but FK-referenced by transaction_line_items) gets
--     additive columns only.
--   * No statement here touches transaction_headers, transaction_items, or
--     anything on their FK path.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. Extend `products` (existing table, 0 rows, FK-referenced by
--    transaction_line_items.product_id — additive/nullable only)
-- ----------------------------------------------------------------------------
ALTER TABLE "products"
  ADD COLUMN "weight" double precision,
  ADD COLUMN "tare_weight" double precision,
  ADD COLUMN "total_weight" double precision,
  ADD COLUMN "sku" text;

-- NOTE: existing `stockno` (unique) already serves the role of Orders-Module's
-- Product.code. Orders-Module's Product.sku is a second, distinct unique
-- identifier in its own schema, so `sku` here is additive, not a duplicate of
-- `stockno`. See report for the mapping: Product.code -> products.stockno,
-- Product.name -> products.description, Product.sku -> products.sku (new).

CREATE UNIQUE INDEX IF NOT EXISTS "products_sku_key" ON "products"("sku") WHERE "sku" IS NOT NULL;

-- ----------------------------------------------------------------------------
-- 2. New table: routes (no FK dependencies)
-- ----------------------------------------------------------------------------
CREATE TABLE "routes" (
  "id"         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name"       TEXT NOT NULL,
  "code"       TEXT NOT NULL,
  "active"     BOOLEAN NOT NULL DEFAULT true,
  "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT now(),
  CONSTRAINT "routes_code_key" UNIQUE ("code")
);

-- ----------------------------------------------------------------------------
-- 3. New table: areas (FK -> routes)
-- ----------------------------------------------------------------------------
CREATE TABLE "areas" (
  "id"               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name"             TEXT NOT NULL,
  "route_id"         INTEGER NOT NULL REFERENCES "routes"("id"),
  "default_sequence" INTEGER,
  "active"           BOOLEAN NOT NULL DEFAULT true,
  "center_lat"       DOUBLE PRECISION,
  "center_lng"       DOUBLE PRECISION,
  "boundary_polygon" TEXT,
  "created_at"       TIMESTAMPTZ(6) NOT NULL DEFAULT now()
);
CREATE INDEX "areas_route_id_idx" ON "areas"("route_id");

-- ----------------------------------------------------------------------------
-- 4. Extend `commercial_customers` (existing table, 536 rows LIVE FINANCIAL
--    DATA — additive/nullable only, no rewrite of existing rows)
-- ----------------------------------------------------------------------------
ALTER TABLE "commercial_customers"
  ADD COLUMN "address"         TEXT,
  ADD COLUMN "lat"             DOUBLE PRECISION,
  ADD COLUMN "lng"             DOUBLE PRECISION,
  ADD COLUMN "google_maps_url" TEXT,
  ADD COLUMN "area_id"         INTEGER REFERENCES "areas"("id"),
  ADD COLUMN "active"          BOOLEAN;

-- NOTE: `notes` intentionally NOT added — commercial_customers already has a
-- `notes text` column. Orders-Module's Customer.notes should read/write that
-- existing column, not a duplicate.
-- NOTE: `email` intentionally NOT added — held back per human decision.
-- No Orders-Module UI/API path was found reading or writing it in the
-- inventory, so it's left out entirely rather than added unused.
-- NOTE: `phone` REMOVED per human decision (2026-08-22 revision). The
-- migrated app writes to the existing `contact_phone` column instead of a
-- new, redundant `phone` column. See Edge Function mapping in the report.
-- NOTE: `account_number` REMOVED per human decision (2026-08-22 revision).
-- Account numbers are read/written through `commercial_customer_accounts`
-- (commercial_customer_accounts.commercial_customer_id -> commercial_customers.id,
-- account_no unique per account) — the normalized, FK'd table that already
-- holds this data (544 rows) — not a flat column on commercial_customers.
-- NOTE: `customer_lane` is left completely untouched — it stays independent,
-- not merged into or aliased by `area_id`.

CREATE INDEX "commercial_customers_area_id_idx" ON "commercial_customers"("area_id");

-- ----------------------------------------------------------------------------
-- 5. New table: vehicles (no FK dependencies)
-- ----------------------------------------------------------------------------
CREATE TABLE "vehicles" (
  "id"           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "registration" TEXT NOT NULL,
  "make"         TEXT,
  "model"        TEXT,
  "capacity"     INTEGER,
  "active"       BOOLEAN NOT NULL DEFAULT true,
  "notes"        TEXT,
  "created_at"   TIMESTAMPTZ(6) NOT NULL DEFAULT now(),
  CONSTRAINT "vehicles_registration_key" UNIQUE ("registration")
);

-- ----------------------------------------------------------------------------
-- 6. New table: drivers (no FK dependencies)
-- ----------------------------------------------------------------------------
CREATE TABLE "drivers" (
  "id"       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name"     TEXT NOT NULL,
  "phone"    TEXT NOT NULL,
  "license"  TEXT,
  "active"   BOOLEAN NOT NULL DEFAULT true,
  "pin_hash" TEXT
);

-- ----------------------------------------------------------------------------
-- 7. New table: driver_auth_tokens (FK -> drivers)
-- ----------------------------------------------------------------------------
CREATE TABLE "driver_auth_tokens" (
  "id"         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "driver_id"  INTEGER NOT NULL REFERENCES "drivers"("id"),
  "token"      TEXT NOT NULL,
  "expires_at" TIMESTAMPTZ(6) NOT NULL,
  "created_at" TIMESTAMPTZ(6) DEFAULT now(),
  "device_id"  TEXT,
  CONSTRAINT "driver_auth_tokens_token_key" UNIQUE ("token")
);
CREATE INDEX "driver_auth_tokens_token_idx" ON "driver_auth_tokens"("token");

-- ----------------------------------------------------------------------------
-- 8. New table: orders (FK -> commercial_customers)
-- ----------------------------------------------------------------------------
CREATE TABLE "orders" (
  "id"                       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_number"             TEXT NOT NULL,
  "customer_id"              UUID NOT NULL REFERENCES "commercial_customers"("id"),
  "order_date"               TIMESTAMPTZ(6) NOT NULL DEFAULT now(),
  "order_type"                TEXT NOT NULL,
  "status"                    TEXT NOT NULL DEFAULT 'pending',
  "requested_delivery_date"   TIMESTAMPTZ(6),
  "priority"                  TEXT NOT NULL DEFAULT 'normal',
  "special_instructions"      TEXT,
  "created_by"                TEXT,
  "created_at"                TIMESTAMPTZ(6) NOT NULL DEFAULT now(),
  "updated_at"                TIMESTAMPTZ(6) NOT NULL,
  CONSTRAINT "orders_order_number_key" UNIQUE ("order_number")
);
CREATE INDEX "orders_customer_id_idx" ON "orders"("customer_id");
CREATE INDEX "orders_order_date_idx" ON "orders"("order_date");
CREATE INDEX "orders_status_idx" ON "orders"("status");

-- ----------------------------------------------------------------------------
-- 9. New table: order_items (FK -> orders, products)
-- ----------------------------------------------------------------------------
CREATE TABLE "order_items" (
  "id"                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id"           INTEGER NOT NULL REFERENCES "orders"("id") ON DELETE CASCADE,
  "product_id"         TEXT NOT NULL REFERENCES "products"("id"),
  "quantity_ordered"   INTEGER NOT NULL,
  "quantity_remaining" INTEGER NOT NULL,
  "notes"              TEXT
);
CREATE INDEX "order_items_order_id_idx" ON "order_items"("order_id");
CREATE INDEX "order_items_product_id_idx" ON "order_items"("product_id");

-- ----------------------------------------------------------------------------
-- 10. New table: order_events (FK -> orders)
--     Added in this revision (was originally deferred to a later phase) —
--     `complete-stop`'s atomic transaction inserts here for its audit trail
--     and cannot be ported without this table existing.
-- ----------------------------------------------------------------------------
CREATE TABLE "order_events" (
  "id"         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id"   INTEGER NOT NULL REFERENCES "orders"("id") ON DELETE CASCADE,
  "type"       TEXT NOT NULL,
  "message"    TEXT NOT NULL,
  "user_id"    TEXT,
  "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT now(),
  "metadata"   JSONB
);
CREATE INDEX "order_events_order_id_idx" ON "order_events"("order_id");

-- ----------------------------------------------------------------------------
-- 11. New table: trips (FK -> vehicles, drivers, routes)
-- ----------------------------------------------------------------------------
CREATE TABLE "trips" (
  "id"                       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "trip_number"              TEXT NOT NULL,
  "trip_date"                TIMESTAMPTZ(6),
  "driver_id"                INTEGER REFERENCES "drivers"("id"),
  "route_id"                 INTEGER REFERENCES "routes"("id"),
  "vehicle_id"               INTEGER NOT NULL REFERENCES "vehicles"("id"),
  "status"                   TEXT NOT NULL DEFAULT 'planned',
  "start_time"               TIMESTAMPTZ(6),
  "end_time"                 TIMESTAMPTZ(6),
  "notes"                    TEXT,
  "created_at"               TIMESTAMPTZ(6) NOT NULL DEFAULT now(),
  "recommendation_snapshot"  JSONB,
  "stock_confirmed"          BOOLEAN NOT NULL DEFAULT false,
  CONSTRAINT "trips_trip_number_key" UNIQUE ("trip_number")
);
CREATE INDEX "trips_trip_date_idx" ON "trips"("trip_date");
CREATE INDEX "trips_driver_id_idx" ON "trips"("driver_id");
CREATE INDEX "trips_route_id_idx" ON "trips"("route_id");

-- ----------------------------------------------------------------------------
-- 12. New table: deliveries (FK -> trips, orders, commercial_customers)
-- ----------------------------------------------------------------------------
CREATE TABLE "deliveries" (
  "id"                      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "trip_id"                 INTEGER REFERENCES "trips"("id"),
  "order_id"                INTEGER NOT NULL REFERENCES "orders"("id"),
  "delivery_number"         INTEGER,
  "customer_id"             UUID NOT NULL REFERENCES "commercial_customers"("id"),
  "delivery_note_number"    INTEGER,
  "delivery_sequence"       INTEGER,
  "status"                  TEXT NOT NULL DEFAULT 'unassigned',
  "delivery_date"           TIMESTAMPTZ(6),
  "actual_delivery_time"    TIMESTAMPTZ(6),
  "is_partial_fulfillment"  BOOLEAN NOT NULL DEFAULT false,
  "special_instructions"    TEXT,
  "notes"                   TEXT,
  "created_at"              TIMESTAMPTZ(6) NOT NULL DEFAULT now(),
  "updated_at"              TIMESTAMPTZ(6) NOT NULL,
  "arrived_at"              TIMESTAMPTZ(6),
  "arrival_gps_lat"         DOUBLE PRECISION,
  "arrival_gps_lng"         DOUBLE PRECISION
);
CREATE INDEX "deliveries_trip_id_idx" ON "deliveries"("trip_id");
CREATE INDEX "deliveries_order_id_idx" ON "deliveries"("order_id");
CREATE INDEX "deliveries_customer_id_idx" ON "deliveries"("customer_id");
CREATE INDEX "deliveries_status_idx" ON "deliveries"("status");

-- ----------------------------------------------------------------------------
-- 13. New table: delivery_items (FK -> deliveries, order_items, products)
-- ----------------------------------------------------------------------------
CREATE TABLE "delivery_items" (
  "id"                       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "delivery_id"              INTEGER NOT NULL REFERENCES "deliveries"("id") ON DELETE CASCADE,
  "order_item_id"            INTEGER NOT NULL REFERENCES "order_items"("id"),
  "product_id"               TEXT NOT NULL REFERENCES "products"("id"),
  "quantity_to_deliver"      INTEGER NOT NULL,
  "quantity_delivered"       INTEGER,
  "quantity_returned_empty"  INTEGER,
  "notes"                    TEXT
);
CREATE INDEX "delivery_items_delivery_id_idx" ON "delivery_items"("delivery_id");
CREATE INDEX "delivery_items_order_item_id_idx" ON "delivery_items"("order_item_id");
CREATE INDEX "delivery_items_product_id_idx" ON "delivery_items"("product_id");

-- ----------------------------------------------------------------------------
-- 14. New table: delivery_returns (FK -> deliveries, products)
-- ----------------------------------------------------------------------------
CREATE TABLE "delivery_returns" (
  "id"                    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "delivery_id"           INTEGER NOT NULL REFERENCES "deliveries"("id") ON DELETE CASCADE,
  "product_id"            TEXT NOT NULL REFERENCES "products"("id"),
  "quantity_returned"     INTEGER NOT NULL,
  "return_condition"      TEXT NOT NULL,
  "erp_credit_note_number" TEXT,
  "notes"                 TEXT,
  "created_at"            TIMESTAMPTZ(6) NOT NULL DEFAULT now()
);
CREATE INDEX "delivery_returns_delivery_id_idx" ON "delivery_returns"("delivery_id");
CREATE INDEX "delivery_returns_product_id_idx" ON "delivery_returns"("product_id");

-- ----------------------------------------------------------------------------
-- 15. New table: delivery_proofs (FK -> deliveries, drivers)
-- ----------------------------------------------------------------------------
CREATE TABLE "delivery_proofs" (
  "id"                      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "delivery_id"             INTEGER NOT NULL REFERENCES "deliveries"("id"),
  "idempotency_key"         TEXT,
  "signature_url"           TEXT,
  "photos"                  TEXT[],
  "arrival_gps_lat"         DOUBLE PRECISION,
  "arrival_gps_lng"         DOUBLE PRECISION,
  "completion_gps_lat"      DOUBLE PRECISION,
  "completion_gps_lng"      DOUBLE PRECISION,
  "delivery_status"         TEXT NOT NULL,
  "failure_reason"          TEXT,
  "failure_code"            TEXT,
  "notes"                   TEXT,
  "completed_by_driver_id"  INTEGER REFERENCES "drivers"("id"),
  "created_at"              TIMESTAMPTZ(6) DEFAULT now(),
  CONSTRAINT "delivery_proofs_delivery_id_key" UNIQUE ("delivery_id"),
  CONSTRAINT "delivery_proofs_idempotency_key_key" UNIQUE ("idempotency_key")
);
CREATE INDEX "delivery_proofs_idempotency_key_idx" ON "delivery_proofs"("idempotency_key");

-- ============================================================================
-- This migration now creates 13 new tables + 2 extensions:
--   routes, areas, vehicles, drivers, driver_auth_tokens, orders, order_items,
--   order_events, trips, deliveries, delivery_items, delivery_returns,
--   delivery_proofs  (13)
--   + ALTER products, ALTER commercial_customers  (2 extensions)
--
-- Still NOT included (deferred to a later phase, per plan):
--   * Setting / settings — app_config already exists and can serve this role;
--     no Edge Function or ported route depends on it existing before Phase 4/5,
--     unlike order_events which was pulled forward in this revision.
-- ============================================================================
